### ISSUE TITLE
Data monitor does not update date selection window

### ISSUE THREAD

**Issue by shallmann** [RNO-G/RNODataViewer#2]
If you look on the online monitor, the max date selectable still refers to the date when the container was pushed. Needs updating to something like datetime.datetime.now() or similar

**Comment by sjoerd-bouma** [comment]
It currently is set to `astropy.time.Time.now()` - I'm a bit surprised that this doesn't update, and I'm not sure this would be fixed by changing to `datetime.datetime.now()`. 

Turns out this does indeed not fix things - the `max_date_allowed` and `date` values just don't get updated after launching the data monitor once. I'll think of a way to have it update regularly...

Should be fixed now! On every page load, we now check if a day has passed, and update the maximum allowed date accordingly.

**Comment by shallmann** [comment]
Thanks, is fixed.
