### ISSUE TITLE
Current use of data monitor

### ISSUE THREAD

**Issue by KelliMichaels** [RNO-G/RNODataViewer#3]
There are a couple issues with following the current installation instructions for the RNODataViewer. First, due to a dash version update I needed to change line 8 in RNODataViewer/RNODataViewer/file_list/file_list to import dash_table from dash instead of from dash.dependencies. I got that one figured out myself but I'm having a further problem. I now successfully execute the code and open the event browser window, but before loading any plots or interacting with the page I get a duplicate callback error like so:
```
In the callback for outout(s):
download file. data
output o (download file.data) is already in use.
Any given output can only have one callback that sets it.
To resolve this situation, try combining these into
one callback function, distinguishing the trigger
by using
"dash.callback context if necessary.
```
Christian and I have both looked around and cannot find the source of this bug. Any ideas? Thanks!

**Comment by shallmann** [comment]
@sjoerd-bouma you use the local version frequently, did you ever encounter a similar problem?

ah ... Whoops.. I think this bug is my fault, because I was playing around and wanted to implement the possibility to directly download files via the monitoring page. I commented it since it anyway does not work as expected as of now. Will develop in a separate branch before merging.

@KelliMichaels , can you try pulling the latest version and try if this error persists?

**Comment by shallmann** [comment]
About the `dash.dependencies` vs `dash` import... these imports also exist in a couple of other python files, so I would be surprised if only in this script changing the import fixes the issue.
... When building the docker container with the Dockerfile, we do not specify a specific version for it to work, right @sjoerd-bouma ?

**Comment by KelliMichaels** [comment]
Works now! Thank you very much
